-- QueryGuard sandbox schema.
--
-- Index coverage here is deliberate. Some columns are indexed so that the
-- planted bugs isolate one problem each; others are left bare on purpose and
-- are marked below. Do not "fix" the missing indexes — the fixtures depend on
-- them.

CREATE TABLE customers (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          VARCHAR(255) NOT NULL,
    full_name      VARCHAR(150) NOT NULL,
    -- PLANTED-BUG SUPPORT: `country` is intentionally left unindexed. It is the
    -- filter column for the JPQL planted bug in CustomerRepository, so adding an
    -- index here would neutralise that fixture.
    country        CHAR(2)      NOT NULL,
    loyalty_tier   VARCHAR(16)  NOT NULL DEFAULT 'STANDARD',
    lifetime_value NUMERIC(12, 2) NOT NULL DEFAULT 0,
    signed_up_at   TIMESTAMPTZ  NOT NULL,
    CONSTRAINT customers_email_key UNIQUE (email)
);

CREATE INDEX idx_customers_signed_up_at ON customers (signed_up_at);

CREATE TABLE orders (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  BIGINT       NOT NULL,
    order_number VARCHAR(32)  NOT NULL,
    status       VARCHAR(16)  NOT NULL,
    total_amount NUMERIC(12, 2) NOT NULL,
    placed_at    TIMESTAMPTZ  NOT NULL,
    CONSTRAINT orders_order_number_key UNIQUE (order_number),
    CONSTRAINT orders_customer_id_fkey
        FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE
);

-- Indexed on purpose: the N+1 fixture should demonstrate round-trip cost, not a
-- sequential scan per iteration.
CREATE INDEX idx_orders_customer_id ON orders (customer_id);
CREATE INDEX idx_orders_placed_at ON orders (placed_at);
CREATE INDEX idx_orders_status ON orders (status);

CREATE TABLE order_items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT       NOT NULL,
    sku          VARCHAR(32)  NOT NULL,
    product_name VARCHAR(200) NOT NULL,
    quantity     INTEGER      NOT NULL CHECK (quantity > 0),
    unit_price   NUMERIC(10, 2) NOT NULL CHECK (unit_price >= 0),
    CONSTRAINT order_items_order_id_fkey
        FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE
);

CREATE INDEX idx_order_items_order_id ON order_items (order_id);
